# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins
import copy
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['ComposableIndexTemplateArgs', 'ComposableIndexTemplate']

@pulumi.input_type
class ComposableIndexTemplateArgs:
    def __init__(__self__, *,
                 body: pulumi.Input[builtins.str],
                 composable_index_template_id: Optional[pulumi.Input[builtins.str]] = None,
                 name: Optional[pulumi.Input[builtins.str]] = None):
        """
        The set of arguments for constructing a ComposableIndexTemplate resource.
        :param pulumi.Input[builtins.str] body: The JSON body of the index template.
        :param pulumi.Input[builtins.str] name: The name of the index template.
        """
        pulumi.set(__self__, "body", body)
        if composable_index_template_id is not None:
            pulumi.set(__self__, "composable_index_template_id", composable_index_template_id)
        if name is not None:
            pulumi.set(__self__, "name", name)

    @property
    @pulumi.getter
    def body(self) -> pulumi.Input[builtins.str]:
        """
        The JSON body of the index template.
        """
        return pulumi.get(self, "body")

    @body.setter
    def body(self, value: pulumi.Input[builtins.str]):
        pulumi.set(self, "body", value)

    @property
    @pulumi.getter(name="composableIndexTemplateId")
    def composable_index_template_id(self) -> Optional[pulumi.Input[builtins.str]]:
        return pulumi.get(self, "composable_index_template_id")

    @composable_index_template_id.setter
    def composable_index_template_id(self, value: Optional[pulumi.Input[builtins.str]]):
        pulumi.set(self, "composable_index_template_id", value)

    @property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[builtins.str]]:
        """
        The name of the index template.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[builtins.str]]):
        pulumi.set(self, "name", value)


@pulumi.input_type
class _ComposableIndexTemplateState:
    def __init__(__self__, *,
                 body: Optional[pulumi.Input[builtins.str]] = None,
                 composable_index_template_id: Optional[pulumi.Input[builtins.str]] = None,
                 name: Optional[pulumi.Input[builtins.str]] = None):
        """
        Input properties used for looking up and filtering ComposableIndexTemplate resources.
        :param pulumi.Input[builtins.str] body: The JSON body of the index template.
        :param pulumi.Input[builtins.str] name: The name of the index template.
        """
        if body is not None:
            pulumi.set(__self__, "body", body)
        if composable_index_template_id is not None:
            pulumi.set(__self__, "composable_index_template_id", composable_index_template_id)
        if name is not None:
            pulumi.set(__self__, "name", name)

    @property
    @pulumi.getter
    def body(self) -> Optional[pulumi.Input[builtins.str]]:
        """
        The JSON body of the index template.
        """
        return pulumi.get(self, "body")

    @body.setter
    def body(self, value: Optional[pulumi.Input[builtins.str]]):
        pulumi.set(self, "body", value)

    @property
    @pulumi.getter(name="composableIndexTemplateId")
    def composable_index_template_id(self) -> Optional[pulumi.Input[builtins.str]]:
        return pulumi.get(self, "composable_index_template_id")

    @composable_index_template_id.setter
    def composable_index_template_id(self, value: Optional[pulumi.Input[builtins.str]]):
        pulumi.set(self, "composable_index_template_id", value)

    @property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[builtins.str]]:
        """
        The name of the index template.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[builtins.str]]):
        pulumi.set(self, "name", value)


@pulumi.type_token("opensearch:index/composableIndexTemplate:ComposableIndexTemplate")
class ComposableIndexTemplate(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 body: Optional[pulumi.Input[builtins.str]] = None,
                 composable_index_template_id: Optional[pulumi.Input[builtins.str]] = None,
                 name: Optional[pulumi.Input[builtins.str]] = None,
                 __props__=None):
        """
        Create a ComposableIndexTemplate resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[builtins.str] body: The JSON body of the index template.
        :param pulumi.Input[builtins.str] name: The name of the index template.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: ComposableIndexTemplateArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a ComposableIndexTemplate resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param ComposableIndexTemplateArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(ComposableIndexTemplateArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 body: Optional[pulumi.Input[builtins.str]] = None,
                 composable_index_template_id: Optional[pulumi.Input[builtins.str]] = None,
                 name: Optional[pulumi.Input[builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = ComposableIndexTemplateArgs.__new__(ComposableIndexTemplateArgs)

            if body is None and not opts.urn:
                raise TypeError("Missing required property 'body'")
            __props__.__dict__["body"] = body
            __props__.__dict__["composable_index_template_id"] = composable_index_template_id
            __props__.__dict__["name"] = name
        super(ComposableIndexTemplate, __self__).__init__(
            'opensearch:index/composableIndexTemplate:ComposableIndexTemplate',
            resource_name,
            __props__,
            opts,
            package_ref=_utilities.get_package())

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            body: Optional[pulumi.Input[builtins.str]] = None,
            composable_index_template_id: Optional[pulumi.Input[builtins.str]] = None,
            name: Optional[pulumi.Input[builtins.str]] = None) -> 'ComposableIndexTemplate':
        """
        Get an existing ComposableIndexTemplate resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[builtins.str] body: The JSON body of the index template.
        :param pulumi.Input[builtins.str] name: The name of the index template.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _ComposableIndexTemplateState.__new__(_ComposableIndexTemplateState)

        __props__.__dict__["body"] = body
        __props__.__dict__["composable_index_template_id"] = composable_index_template_id
        __props__.__dict__["name"] = name
        return ComposableIndexTemplate(resource_name, opts=opts, __props__=__props__)

    @property
    @pulumi.getter
    def body(self) -> pulumi.Output[builtins.str]:
        """
        The JSON body of the index template.
        """
        return pulumi.get(self, "body")

    @property
    @pulumi.getter(name="composableIndexTemplateId")
    def composable_index_template_id(self) -> pulumi.Output[builtins.str]:
        return pulumi.get(self, "composable_index_template_id")

    @property
    @pulumi.getter
    def name(self) -> pulumi.Output[builtins.str]:
        """
        The name of the index template.
        """
        return pulumi.get(self, "name")

