# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins
import copy
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['DashboardTenantArgs', 'DashboardTenant']

@pulumi.input_type
class DashboardTenantArgs:
    def __init__(__self__, *,
                 tenant_name: pulumi.Input[builtins.str],
                 dashboard_tenant_id: Optional[pulumi.Input[builtins.str]] = None,
                 description: Optional[pulumi.Input[builtins.str]] = None):
        """
        The set of arguments for constructing a DashboardTenant resource.
        :param pulumi.Input[builtins.str] tenant_name: The name of the tenant.
        :param pulumi.Input[builtins.str] description: Description of the tenant.
        """
        pulumi.set(__self__, "tenant_name", tenant_name)
        if dashboard_tenant_id is not None:
            pulumi.set(__self__, "dashboard_tenant_id", dashboard_tenant_id)
        if description is not None:
            pulumi.set(__self__, "description", description)

    @property
    @pulumi.getter(name="tenantName")
    def tenant_name(self) -> pulumi.Input[builtins.str]:
        """
        The name of the tenant.
        """
        return pulumi.get(self, "tenant_name")

    @tenant_name.setter
    def tenant_name(self, value: pulumi.Input[builtins.str]):
        pulumi.set(self, "tenant_name", value)

    @property
    @pulumi.getter(name="dashboardTenantId")
    def dashboard_tenant_id(self) -> Optional[pulumi.Input[builtins.str]]:
        return pulumi.get(self, "dashboard_tenant_id")

    @dashboard_tenant_id.setter
    def dashboard_tenant_id(self, value: Optional[pulumi.Input[builtins.str]]):
        pulumi.set(self, "dashboard_tenant_id", value)

    @property
    @pulumi.getter
    def description(self) -> Optional[pulumi.Input[builtins.str]]:
        """
        Description of the tenant.
        """
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: Optional[pulumi.Input[builtins.str]]):
        pulumi.set(self, "description", value)


@pulumi.input_type
class _DashboardTenantState:
    def __init__(__self__, *,
                 dashboard_tenant_id: Optional[pulumi.Input[builtins.str]] = None,
                 description: Optional[pulumi.Input[builtins.str]] = None,
                 index: Optional[pulumi.Input[builtins.str]] = None,
                 tenant_name: Optional[pulumi.Input[builtins.str]] = None):
        """
        Input properties used for looking up and filtering DashboardTenant resources.
        :param pulumi.Input[builtins.str] description: Description of the tenant.
        :param pulumi.Input[builtins.str] tenant_name: The name of the tenant.
        """
        if dashboard_tenant_id is not None:
            pulumi.set(__self__, "dashboard_tenant_id", dashboard_tenant_id)
        if description is not None:
            pulumi.set(__self__, "description", description)
        if index is not None:
            pulumi.set(__self__, "index", index)
        if tenant_name is not None:
            pulumi.set(__self__, "tenant_name", tenant_name)

    @property
    @pulumi.getter(name="dashboardTenantId")
    def dashboard_tenant_id(self) -> Optional[pulumi.Input[builtins.str]]:
        return pulumi.get(self, "dashboard_tenant_id")

    @dashboard_tenant_id.setter
    def dashboard_tenant_id(self, value: Optional[pulumi.Input[builtins.str]]):
        pulumi.set(self, "dashboard_tenant_id", value)

    @property
    @pulumi.getter
    def description(self) -> Optional[pulumi.Input[builtins.str]]:
        """
        Description of the tenant.
        """
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: Optional[pulumi.Input[builtins.str]]):
        pulumi.set(self, "description", value)

    @property
    @pulumi.getter
    def index(self) -> Optional[pulumi.Input[builtins.str]]:
        return pulumi.get(self, "index")

    @index.setter
    def index(self, value: Optional[pulumi.Input[builtins.str]]):
        pulumi.set(self, "index", value)

    @property
    @pulumi.getter(name="tenantName")
    def tenant_name(self) -> Optional[pulumi.Input[builtins.str]]:
        """
        The name of the tenant.
        """
        return pulumi.get(self, "tenant_name")

    @tenant_name.setter
    def tenant_name(self, value: Optional[pulumi.Input[builtins.str]]):
        pulumi.set(self, "tenant_name", value)


@pulumi.type_token("opensearch:index/dashboardTenant:DashboardTenant")
class DashboardTenant(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 dashboard_tenant_id: Optional[pulumi.Input[builtins.str]] = None,
                 description: Optional[pulumi.Input[builtins.str]] = None,
                 tenant_name: Optional[pulumi.Input[builtins.str]] = None,
                 __props__=None):
        """
        Create a DashboardTenant resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[builtins.str] description: Description of the tenant.
        :param pulumi.Input[builtins.str] tenant_name: The name of the tenant.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: DashboardTenantArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a DashboardTenant resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param DashboardTenantArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(DashboardTenantArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 dashboard_tenant_id: Optional[pulumi.Input[builtins.str]] = None,
                 description: Optional[pulumi.Input[builtins.str]] = None,
                 tenant_name: Optional[pulumi.Input[builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = DashboardTenantArgs.__new__(DashboardTenantArgs)

            __props__.__dict__["dashboard_tenant_id"] = dashboard_tenant_id
            __props__.__dict__["description"] = description
            if tenant_name is None and not opts.urn:
                raise TypeError("Missing required property 'tenant_name'")
            __props__.__dict__["tenant_name"] = tenant_name
            __props__.__dict__["index"] = None
        super(DashboardTenant, __self__).__init__(
            'opensearch:index/dashboardTenant:DashboardTenant',
            resource_name,
            __props__,
            opts,
            package_ref=_utilities.get_package())

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            dashboard_tenant_id: Optional[pulumi.Input[builtins.str]] = None,
            description: Optional[pulumi.Input[builtins.str]] = None,
            index: Optional[pulumi.Input[builtins.str]] = None,
            tenant_name: Optional[pulumi.Input[builtins.str]] = None) -> 'DashboardTenant':
        """
        Get an existing DashboardTenant resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[builtins.str] description: Description of the tenant.
        :param pulumi.Input[builtins.str] tenant_name: The name of the tenant.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _DashboardTenantState.__new__(_DashboardTenantState)

        __props__.__dict__["dashboard_tenant_id"] = dashboard_tenant_id
        __props__.__dict__["description"] = description
        __props__.__dict__["index"] = index
        __props__.__dict__["tenant_name"] = tenant_name
        return DashboardTenant(resource_name, opts=opts, __props__=__props__)

    @property
    @pulumi.getter(name="dashboardTenantId")
    def dashboard_tenant_id(self) -> pulumi.Output[builtins.str]:
        return pulumi.get(self, "dashboard_tenant_id")

    @property
    @pulumi.getter
    def description(self) -> pulumi.Output[Optional[builtins.str]]:
        """
        Description of the tenant.
        """
        return pulumi.get(self, "description")

    @property
    @pulumi.getter
    def index(self) -> pulumi.Output[builtins.str]:
        return pulumi.get(self, "index")

    @property
    @pulumi.getter(name="tenantName")
    def tenant_name(self) -> pulumi.Output[builtins.str]:
        """
        The name of the tenant.
        """
        return pulumi.get(self, "tenant_name")

