# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins
import copy
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['DataStreamArgs', 'DataStream']

@pulumi.input_type
class DataStreamArgs:
    def __init__(__self__, *,
                 data_stream_id: Optional[pulumi.Input[builtins.str]] = None,
                 name: Optional[pulumi.Input[builtins.str]] = None):
        """
        The set of arguments for constructing a DataStream resource.
        :param pulumi.Input[builtins.str] name: Name of the data stream to create, must have a matching
        """
        if data_stream_id is not None:
            pulumi.set(__self__, "data_stream_id", data_stream_id)
        if name is not None:
            pulumi.set(__self__, "name", name)

    @property
    @pulumi.getter(name="dataStreamId")
    def data_stream_id(self) -> Optional[pulumi.Input[builtins.str]]:
        return pulumi.get(self, "data_stream_id")

    @data_stream_id.setter
    def data_stream_id(self, value: Optional[pulumi.Input[builtins.str]]):
        pulumi.set(self, "data_stream_id", value)

    @property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[builtins.str]]:
        """
        Name of the data stream to create, must have a matching
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[builtins.str]]):
        pulumi.set(self, "name", value)


@pulumi.input_type
class _DataStreamState:
    def __init__(__self__, *,
                 data_stream_id: Optional[pulumi.Input[builtins.str]] = None,
                 name: Optional[pulumi.Input[builtins.str]] = None):
        """
        Input properties used for looking up and filtering DataStream resources.
        :param pulumi.Input[builtins.str] name: Name of the data stream to create, must have a matching
        """
        if data_stream_id is not None:
            pulumi.set(__self__, "data_stream_id", data_stream_id)
        if name is not None:
            pulumi.set(__self__, "name", name)

    @property
    @pulumi.getter(name="dataStreamId")
    def data_stream_id(self) -> Optional[pulumi.Input[builtins.str]]:
        return pulumi.get(self, "data_stream_id")

    @data_stream_id.setter
    def data_stream_id(self, value: Optional[pulumi.Input[builtins.str]]):
        pulumi.set(self, "data_stream_id", value)

    @property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[builtins.str]]:
        """
        Name of the data stream to create, must have a matching
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[builtins.str]]):
        pulumi.set(self, "name", value)


@pulumi.type_token("opensearch:index/dataStream:DataStream")
class DataStream(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 data_stream_id: Optional[pulumi.Input[builtins.str]] = None,
                 name: Optional[pulumi.Input[builtins.str]] = None,
                 __props__=None):
        """
        Create a DataStream resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[builtins.str] name: Name of the data stream to create, must have a matching
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: Optional[DataStreamArgs] = None,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a DataStream resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param DataStreamArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(DataStreamArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 data_stream_id: Optional[pulumi.Input[builtins.str]] = None,
                 name: Optional[pulumi.Input[builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = DataStreamArgs.__new__(DataStreamArgs)

            __props__.__dict__["data_stream_id"] = data_stream_id
            __props__.__dict__["name"] = name
        super(DataStream, __self__).__init__(
            'opensearch:index/dataStream:DataStream',
            resource_name,
            __props__,
            opts,
            package_ref=_utilities.get_package())

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            data_stream_id: Optional[pulumi.Input[builtins.str]] = None,
            name: Optional[pulumi.Input[builtins.str]] = None) -> 'DataStream':
        """
        Get an existing DataStream resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[builtins.str] name: Name of the data stream to create, must have a matching
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _DataStreamState.__new__(_DataStreamState)

        __props__.__dict__["data_stream_id"] = data_stream_id
        __props__.__dict__["name"] = name
        return DataStream(resource_name, opts=opts, __props__=__props__)

    @property
    @pulumi.getter(name="dataStreamId")
    def data_stream_id(self) -> pulumi.Output[builtins.str]:
        return pulumi.get(self, "data_stream_id")

    @property
    @pulumi.getter
    def name(self) -> pulumi.Output[builtins.str]:
        """
        Name of the data stream to create, must have a matching
        """
        return pulumi.get(self, "name")

