# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins
import copy
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs
from ._inputs import *

__all__ = ['IsmPolicyMappingArgs', 'IsmPolicyMapping']

@pulumi.input_type
class IsmPolicyMappingArgs:
    def __init__(__self__, *,
                 indexes: pulumi.Input[builtins.str],
                 policy_id: pulumi.Input[builtins.str],
                 includes: Optional[pulumi.Input[Sequence[pulumi.Input[Mapping[str, pulumi.Input[builtins.str]]]]]] = None,
                 is_safe: Optional[pulumi.Input[builtins.bool]] = None,
                 ism_policy_mapping_id: Optional[pulumi.Input[builtins.str]] = None,
                 managed_indexes: Optional[pulumi.Input[Sequence[pulumi.Input[builtins.str]]]] = None,
                 state: Optional[pulumi.Input[builtins.str]] = None,
                 timeouts: Optional[pulumi.Input['IsmPolicyMappingTimeoutsArgs']] = None):
        """
        The set of arguments for constructing a IsmPolicyMapping resource.
        :param pulumi.Input[builtins.str] indexes: Name of the index to apply the policy to. You can use an index pattern to update multiple indices at once.
        :param pulumi.Input[builtins.str] policy_id: The name of the policy.
        :param pulumi.Input[Sequence[pulumi.Input[Mapping[str, pulumi.Input[builtins.str]]]]] includes: When updating multiple indices, you might want to include a state filter to only affect certain managed indices. The
               background process only applies the change if the index is currently in the state specified.
        :param pulumi.Input[builtins.str] state: After a change in policy takes place, specify the state for the index to transition to
        """
        pulumi.set(__self__, "indexes", indexes)
        pulumi.set(__self__, "policy_id", policy_id)
        if includes is not None:
            pulumi.set(__self__, "includes", includes)
        if is_safe is not None:
            pulumi.set(__self__, "is_safe", is_safe)
        if ism_policy_mapping_id is not None:
            pulumi.set(__self__, "ism_policy_mapping_id", ism_policy_mapping_id)
        if managed_indexes is not None:
            pulumi.set(__self__, "managed_indexes", managed_indexes)
        if state is not None:
            pulumi.set(__self__, "state", state)
        if timeouts is not None:
            pulumi.set(__self__, "timeouts", timeouts)

    @property
    @pulumi.getter
    def indexes(self) -> pulumi.Input[builtins.str]:
        """
        Name of the index to apply the policy to. You can use an index pattern to update multiple indices at once.
        """
        return pulumi.get(self, "indexes")

    @indexes.setter
    def indexes(self, value: pulumi.Input[builtins.str]):
        pulumi.set(self, "indexes", value)

    @property
    @pulumi.getter(name="policyId")
    def policy_id(self) -> pulumi.Input[builtins.str]:
        """
        The name of the policy.
        """
        return pulumi.get(self, "policy_id")

    @policy_id.setter
    def policy_id(self, value: pulumi.Input[builtins.str]):
        pulumi.set(self, "policy_id", value)

    @property
    @pulumi.getter
    def includes(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[Mapping[str, pulumi.Input[builtins.str]]]]]]:
        """
        When updating multiple indices, you might want to include a state filter to only affect certain managed indices. The
        background process only applies the change if the index is currently in the state specified.
        """
        return pulumi.get(self, "includes")

    @includes.setter
    def includes(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[Mapping[str, pulumi.Input[builtins.str]]]]]]):
        pulumi.set(self, "includes", value)

    @property
    @pulumi.getter(name="isSafe")
    def is_safe(self) -> Optional[pulumi.Input[builtins.bool]]:
        return pulumi.get(self, "is_safe")

    @is_safe.setter
    def is_safe(self, value: Optional[pulumi.Input[builtins.bool]]):
        pulumi.set(self, "is_safe", value)

    @property
    @pulumi.getter(name="ismPolicyMappingId")
    def ism_policy_mapping_id(self) -> Optional[pulumi.Input[builtins.str]]:
        return pulumi.get(self, "ism_policy_mapping_id")

    @ism_policy_mapping_id.setter
    def ism_policy_mapping_id(self, value: Optional[pulumi.Input[builtins.str]]):
        pulumi.set(self, "ism_policy_mapping_id", value)

    @property
    @pulumi.getter(name="managedIndexes")
    def managed_indexes(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[builtins.str]]]]:
        return pulumi.get(self, "managed_indexes")

    @managed_indexes.setter
    def managed_indexes(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[builtins.str]]]]):
        pulumi.set(self, "managed_indexes", value)

    @property
    @pulumi.getter
    def state(self) -> Optional[pulumi.Input[builtins.str]]:
        """
        After a change in policy takes place, specify the state for the index to transition to
        """
        return pulumi.get(self, "state")

    @state.setter
    def state(self, value: Optional[pulumi.Input[builtins.str]]):
        pulumi.set(self, "state", value)

    @property
    @pulumi.getter
    def timeouts(self) -> Optional[pulumi.Input['IsmPolicyMappingTimeoutsArgs']]:
        return pulumi.get(self, "timeouts")

    @timeouts.setter
    def timeouts(self, value: Optional[pulumi.Input['IsmPolicyMappingTimeoutsArgs']]):
        pulumi.set(self, "timeouts", value)


@pulumi.input_type
class _IsmPolicyMappingState:
    def __init__(__self__, *,
                 includes: Optional[pulumi.Input[Sequence[pulumi.Input[Mapping[str, pulumi.Input[builtins.str]]]]]] = None,
                 indexes: Optional[pulumi.Input[builtins.str]] = None,
                 is_safe: Optional[pulumi.Input[builtins.bool]] = None,
                 ism_policy_mapping_id: Optional[pulumi.Input[builtins.str]] = None,
                 managed_indexes: Optional[pulumi.Input[Sequence[pulumi.Input[builtins.str]]]] = None,
                 policy_id: Optional[pulumi.Input[builtins.str]] = None,
                 state: Optional[pulumi.Input[builtins.str]] = None,
                 timeouts: Optional[pulumi.Input['IsmPolicyMappingTimeoutsArgs']] = None):
        """
        Input properties used for looking up and filtering IsmPolicyMapping resources.
        :param pulumi.Input[Sequence[pulumi.Input[Mapping[str, pulumi.Input[builtins.str]]]]] includes: When updating multiple indices, you might want to include a state filter to only affect certain managed indices. The
               background process only applies the change if the index is currently in the state specified.
        :param pulumi.Input[builtins.str] indexes: Name of the index to apply the policy to. You can use an index pattern to update multiple indices at once.
        :param pulumi.Input[builtins.str] policy_id: The name of the policy.
        :param pulumi.Input[builtins.str] state: After a change in policy takes place, specify the state for the index to transition to
        """
        if includes is not None:
            pulumi.set(__self__, "includes", includes)
        if indexes is not None:
            pulumi.set(__self__, "indexes", indexes)
        if is_safe is not None:
            pulumi.set(__self__, "is_safe", is_safe)
        if ism_policy_mapping_id is not None:
            pulumi.set(__self__, "ism_policy_mapping_id", ism_policy_mapping_id)
        if managed_indexes is not None:
            pulumi.set(__self__, "managed_indexes", managed_indexes)
        if policy_id is not None:
            pulumi.set(__self__, "policy_id", policy_id)
        if state is not None:
            pulumi.set(__self__, "state", state)
        if timeouts is not None:
            pulumi.set(__self__, "timeouts", timeouts)

    @property
    @pulumi.getter
    def includes(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[Mapping[str, pulumi.Input[builtins.str]]]]]]:
        """
        When updating multiple indices, you might want to include a state filter to only affect certain managed indices. The
        background process only applies the change if the index is currently in the state specified.
        """
        return pulumi.get(self, "includes")

    @includes.setter
    def includes(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[Mapping[str, pulumi.Input[builtins.str]]]]]]):
        pulumi.set(self, "includes", value)

    @property
    @pulumi.getter
    def indexes(self) -> Optional[pulumi.Input[builtins.str]]:
        """
        Name of the index to apply the policy to. You can use an index pattern to update multiple indices at once.
        """
        return pulumi.get(self, "indexes")

    @indexes.setter
    def indexes(self, value: Optional[pulumi.Input[builtins.str]]):
        pulumi.set(self, "indexes", value)

    @property
    @pulumi.getter(name="isSafe")
    def is_safe(self) -> Optional[pulumi.Input[builtins.bool]]:
        return pulumi.get(self, "is_safe")

    @is_safe.setter
    def is_safe(self, value: Optional[pulumi.Input[builtins.bool]]):
        pulumi.set(self, "is_safe", value)

    @property
    @pulumi.getter(name="ismPolicyMappingId")
    def ism_policy_mapping_id(self) -> Optional[pulumi.Input[builtins.str]]:
        return pulumi.get(self, "ism_policy_mapping_id")

    @ism_policy_mapping_id.setter
    def ism_policy_mapping_id(self, value: Optional[pulumi.Input[builtins.str]]):
        pulumi.set(self, "ism_policy_mapping_id", value)

    @property
    @pulumi.getter(name="managedIndexes")
    def managed_indexes(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[builtins.str]]]]:
        return pulumi.get(self, "managed_indexes")

    @managed_indexes.setter
    def managed_indexes(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[builtins.str]]]]):
        pulumi.set(self, "managed_indexes", value)

    @property
    @pulumi.getter(name="policyId")
    def policy_id(self) -> Optional[pulumi.Input[builtins.str]]:
        """
        The name of the policy.
        """
        return pulumi.get(self, "policy_id")

    @policy_id.setter
    def policy_id(self, value: Optional[pulumi.Input[builtins.str]]):
        pulumi.set(self, "policy_id", value)

    @property
    @pulumi.getter
    def state(self) -> Optional[pulumi.Input[builtins.str]]:
        """
        After a change in policy takes place, specify the state for the index to transition to
        """
        return pulumi.get(self, "state")

    @state.setter
    def state(self, value: Optional[pulumi.Input[builtins.str]]):
        pulumi.set(self, "state", value)

    @property
    @pulumi.getter
    def timeouts(self) -> Optional[pulumi.Input['IsmPolicyMappingTimeoutsArgs']]:
        return pulumi.get(self, "timeouts")

    @timeouts.setter
    def timeouts(self, value: Optional[pulumi.Input['IsmPolicyMappingTimeoutsArgs']]):
        pulumi.set(self, "timeouts", value)


@pulumi.type_token("opensearch:index/ismPolicyMapping:IsmPolicyMapping")
class IsmPolicyMapping(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 includes: Optional[pulumi.Input[Sequence[pulumi.Input[Mapping[str, pulumi.Input[builtins.str]]]]]] = None,
                 indexes: Optional[pulumi.Input[builtins.str]] = None,
                 is_safe: Optional[pulumi.Input[builtins.bool]] = None,
                 ism_policy_mapping_id: Optional[pulumi.Input[builtins.str]] = None,
                 managed_indexes: Optional[pulumi.Input[Sequence[pulumi.Input[builtins.str]]]] = None,
                 policy_id: Optional[pulumi.Input[builtins.str]] = None,
                 state: Optional[pulumi.Input[builtins.str]] = None,
                 timeouts: Optional[pulumi.Input[Union['IsmPolicyMappingTimeoutsArgs', 'IsmPolicyMappingTimeoutsArgsDict']]] = None,
                 __props__=None):
        """
        Create a IsmPolicyMapping resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[Sequence[pulumi.Input[Mapping[str, pulumi.Input[builtins.str]]]]] includes: When updating multiple indices, you might want to include a state filter to only affect certain managed indices. The
               background process only applies the change if the index is currently in the state specified.
        :param pulumi.Input[builtins.str] indexes: Name of the index to apply the policy to. You can use an index pattern to update multiple indices at once.
        :param pulumi.Input[builtins.str] policy_id: The name of the policy.
        :param pulumi.Input[builtins.str] state: After a change in policy takes place, specify the state for the index to transition to
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: IsmPolicyMappingArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a IsmPolicyMapping resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param IsmPolicyMappingArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(IsmPolicyMappingArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 includes: Optional[pulumi.Input[Sequence[pulumi.Input[Mapping[str, pulumi.Input[builtins.str]]]]]] = None,
                 indexes: Optional[pulumi.Input[builtins.str]] = None,
                 is_safe: Optional[pulumi.Input[builtins.bool]] = None,
                 ism_policy_mapping_id: Optional[pulumi.Input[builtins.str]] = None,
                 managed_indexes: Optional[pulumi.Input[Sequence[pulumi.Input[builtins.str]]]] = None,
                 policy_id: Optional[pulumi.Input[builtins.str]] = None,
                 state: Optional[pulumi.Input[builtins.str]] = None,
                 timeouts: Optional[pulumi.Input[Union['IsmPolicyMappingTimeoutsArgs', 'IsmPolicyMappingTimeoutsArgsDict']]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = IsmPolicyMappingArgs.__new__(IsmPolicyMappingArgs)

            __props__.__dict__["includes"] = includes
            if indexes is None and not opts.urn:
                raise TypeError("Missing required property 'indexes'")
            __props__.__dict__["indexes"] = indexes
            __props__.__dict__["is_safe"] = is_safe
            __props__.__dict__["ism_policy_mapping_id"] = ism_policy_mapping_id
            __props__.__dict__["managed_indexes"] = managed_indexes
            if policy_id is None and not opts.urn:
                raise TypeError("Missing required property 'policy_id'")
            __props__.__dict__["policy_id"] = policy_id
            __props__.__dict__["state"] = state
            __props__.__dict__["timeouts"] = timeouts
        super(IsmPolicyMapping, __self__).__init__(
            'opensearch:index/ismPolicyMapping:IsmPolicyMapping',
            resource_name,
            __props__,
            opts,
            package_ref=_utilities.get_package())

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            includes: Optional[pulumi.Input[Sequence[pulumi.Input[Mapping[str, pulumi.Input[builtins.str]]]]]] = None,
            indexes: Optional[pulumi.Input[builtins.str]] = None,
            is_safe: Optional[pulumi.Input[builtins.bool]] = None,
            ism_policy_mapping_id: Optional[pulumi.Input[builtins.str]] = None,
            managed_indexes: Optional[pulumi.Input[Sequence[pulumi.Input[builtins.str]]]] = None,
            policy_id: Optional[pulumi.Input[builtins.str]] = None,
            state: Optional[pulumi.Input[builtins.str]] = None,
            timeouts: Optional[pulumi.Input[Union['IsmPolicyMappingTimeoutsArgs', 'IsmPolicyMappingTimeoutsArgsDict']]] = None) -> 'IsmPolicyMapping':
        """
        Get an existing IsmPolicyMapping resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[Sequence[pulumi.Input[Mapping[str, pulumi.Input[builtins.str]]]]] includes: When updating multiple indices, you might want to include a state filter to only affect certain managed indices. The
               background process only applies the change if the index is currently in the state specified.
        :param pulumi.Input[builtins.str] indexes: Name of the index to apply the policy to. You can use an index pattern to update multiple indices at once.
        :param pulumi.Input[builtins.str] policy_id: The name of the policy.
        :param pulumi.Input[builtins.str] state: After a change in policy takes place, specify the state for the index to transition to
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _IsmPolicyMappingState.__new__(_IsmPolicyMappingState)

        __props__.__dict__["includes"] = includes
        __props__.__dict__["indexes"] = indexes
        __props__.__dict__["is_safe"] = is_safe
        __props__.__dict__["ism_policy_mapping_id"] = ism_policy_mapping_id
        __props__.__dict__["managed_indexes"] = managed_indexes
        __props__.__dict__["policy_id"] = policy_id
        __props__.__dict__["state"] = state
        __props__.__dict__["timeouts"] = timeouts
        return IsmPolicyMapping(resource_name, opts=opts, __props__=__props__)

    @property
    @pulumi.getter
    def includes(self) -> pulumi.Output[Optional[Sequence[Mapping[str, builtins.str]]]]:
        """
        When updating multiple indices, you might want to include a state filter to only affect certain managed indices. The
        background process only applies the change if the index is currently in the state specified.
        """
        return pulumi.get(self, "includes")

    @property
    @pulumi.getter
    def indexes(self) -> pulumi.Output[builtins.str]:
        """
        Name of the index to apply the policy to. You can use an index pattern to update multiple indices at once.
        """
        return pulumi.get(self, "indexes")

    @property
    @pulumi.getter(name="isSafe")
    def is_safe(self) -> pulumi.Output[Optional[builtins.bool]]:
        return pulumi.get(self, "is_safe")

    @property
    @pulumi.getter(name="ismPolicyMappingId")
    def ism_policy_mapping_id(self) -> pulumi.Output[builtins.str]:
        return pulumi.get(self, "ism_policy_mapping_id")

    @property
    @pulumi.getter(name="managedIndexes")
    def managed_indexes(self) -> pulumi.Output[Sequence[builtins.str]]:
        return pulumi.get(self, "managed_indexes")

    @property
    @pulumi.getter(name="policyId")
    def policy_id(self) -> pulumi.Output[builtins.str]:
        """
        The name of the policy.
        """
        return pulumi.get(self, "policy_id")

    @property
    @pulumi.getter
    def state(self) -> pulumi.Output[Optional[builtins.str]]:
        """
        After a change in policy takes place, specify the state for the index to transition to
        """
        return pulumi.get(self, "state")

    @property
    @pulumi.getter
    def timeouts(self) -> pulumi.Output[Optional['outputs.IsmPolicyMappingTimeouts']]:
        return pulumi.get(self, "timeouts")

