repos:
  - repo: https://github.com/gitguardian/ggshield
    rev: v1.39.0
    hooks:
      - id: ggshield
        language_version: python3
        stages: [commit, push]
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.7.2
    hooks:
      - id: commitizen
