name: Pulumi Preview Prod Update
on:
  pull_request:
    branches:
      - main
jobs:
  preview:
    name: Preview Prod Update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
      - name: Install dependencies
        run: poetry install
      - uses: pulumi/actions@v6
        with:
          command: preview
          stack-name: HuckStream/Pipeline/prod
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
