name: Pulumi Update Sandbox
on:
  push:
    branches:
      - sbx
jobs:
  update:
    name: Update Sandbox
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: package.json
      - run: npm install
      - uses: pulumi/actions@v6
        with:
          command: up
          stack-name: HuckStream/Pulumi-Example-Any-TF/sbx
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
